schemas:
    $define:
        $link:  type=string;
        $text:  type=string;
        
        $name:  type=string;
        $mail:  type=string; mask=".+@.+"

        $rat_tag:   type=string; values=[data, hmi, hw, sw];
        $rat_tags:  type=list<$rat_tag>;
        
        $srs_tag:   type=string; values=[some_stuff_from_srs];
        $srs_tags:  type=list<$rat_tag>;
        
                
    requirement:
        origin:         $link
        text:           $text
        analysis:
            author-mail:            $mail
            feasibility-study:      $text
            approach-to-address:    $text
            assumptions:            $text
        status:
            input:          type=string; values=[new, updated, confirmed, rejected]

linkage:
    - rat.rid [*] <- [*] prs.origin

gates:
    0:  name: valid
        test: 
            - verify_file_structure
            - verify_syntax
    1:  name: detalized
        test:
            - verify_requirement_schema
    2:  name: cute
        test:
            - verify_cuteness
    3:  name: traceable
        test:
            - verify_link_direction
            - verify_link_relations
    4:  name: consistent
        test:
            - verify_derived_statuses
    5:  name: ready
        test:
            - verify_acceptance_statuses